#!/usr/bin/env sh
# SPDX-License-Identifier: GPL-3.0-or-later
# The repository and published hook use one local matching implementation.

exec node "$(dirname "$0")/../githooks/commit-message.mjs" "$1"
