// SPDX-License-Identifier: GPL-3.0-or-later
import { afterAll, describe, expect, it } from "vitest";
import { mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { identities, phrases, mailboxes } from "../githooks/attribution.mjs";
import { accepted, rejected } from "./fixtures/attribution-fixtures.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));
const scratch = mkdtempSync(path.join(tmpdir(), "attribution-hooks-"));
const consumer = path.join(scratch, "thalorna consumer");
mkdirSync(consumer);
const env = {
    ...process.env,
    GIT_CONFIG_NOSYSTEM: "1",
    GIT_CONFIG_GLOBAL: path.join(scratch, "gitconfig"),
    GIT_CONFIG_COUNT: "0",
    npm_config_cache: path.join(scratch, "npm-cache"),
    LC_ALL: "C",
};
for (const key of ["GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_COMMON_DIR"]) delete env[key];
spawnSync("git", ["init", "--quiet", consumer], { env });
afterAll(() => rmSync(scratch, { recursive: true, force: true }));

function runHook(hook: string, content: string, enabled?: boolean) {
    const message = path.join(scratch, "commit message");
    writeFileSync(message, content);
    const config =
        enabled === undefined ?
            {}
        :   {
                GIT_CONFIG_COUNT: "1",
                GIT_CONFIG_KEY_0: "hooks.noAttribution",
                GIT_CONFIG_VALUE_0: String(enabled),
            };
    return spawnSync("sh", [hook, message], {
        cwd: consumer,
        env: { ...env, ...config },
        encoding: "utf8",
    });
}

const cases: [string, boolean][] = [
    ...accepted.map((message): [string, boolean] => [message, false]),
    ...rejected.map((message): [string, boolean] => [message, true]),
    ...identities.flatMap((name) => [
        [`Co-Authored-By: ${name} <contributor@example.com>`, true] as [string, boolean],
        ...phrases.map((phrase): [string, boolean] => [`${phrase} ${name}`, true]),
    ]),
    ...mailboxes.map((mailbox): [string, boolean] => [
        `Co-Authored-By: Contributor <${mailbox}>`,
        true,
    ]),
];

for (const entry of ["githooks/commit-msg", ".githooks/commit-msg"]) {
    describe(entry, () => {
        const hook = path.join(root, entry);
        it.each(cases)("classifies %s", (message, rejected) => {
            const result = runHook(hook, message, true);
            expect(result.status, result.stderr).toBe(rejected ? 1 : 0);
        });
        it("reports original lines and columns after comments and decoration", () => {
            const result = runHook(
                hook,
                "Subject\r\n# comment\r\n\r\n  🤖 **Generated with** [Codex](https://openai.com/codex)\r\n",
            );
            expect(result.status).toBe(1);
            expect(result.stderr).toContain(":4:8: error:");
        });
        it("runs directly through the portable shell shebang", () => {
            const message = path.join(scratch, "direct message");
            writeFileSync(message, "Generated by ChatGPT");
            const result = spawnSync(hook, [message], { cwd: consumer, env, encoding: "utf8" });
            expect(result.status, result.stderr).toBe(1);
        });
        it("ignores comment lines and the verbose diff after scissors", () => {
            expect(
                runHook(
                    hook,
                    "Subject\n# Co-Authored-By: Claude <noreply@anthropic.com>\n# ------------------------ >8 ------------------------\nGenerated with Claude Code\n",
                ).status,
            ).toBe(0);
        });
        it("checks attribution before scissors", () => {
            expect(
                runHook(hook, "Subject\n\nGenerated with Claude Code\n# -------- >8 --------\n")
                    .status,
            ).toBe(1);
        });
    });
}
it("allows the shipped hook to opt out", () => {
    expect(
        runHook(path.join(root, "githooks/commit-msg"), "Generated with Claude Code", false).status,
    ).toBe(0);
});
it("keeps the repository hook enabled independently of the consumer switch", () => {
    expect(
        runHook(path.join(root, ".githooks/commit-msg"), "Generated with Claude Code", false)
            .status,
    ).toBe(1);
});

it("ships every hook dependency and runs the installed hook in a consumer", () => {
    const packed = spawnSync(
        "npm",
        ["pack", "--ignore-scripts", "--json", "--pack-destination", scratch],
        { cwd: root, env, encoding: "utf8" },
    );
    expect(packed.status, packed.stderr).toBe(0);
    const [manifest] = JSON.parse(packed.stdout);
    const shipped = new Set(manifest.files.map((file: { path: string }) => file.path));
    const visited = new Set<string>();
    function visit(relative: string) {
        if (visited.has(relative)) return;
        visited.add(relative);
        expect(shipped.has(relative), `Missing published hook dependency: ${relative}`).toBe(true);
        const source = readFileSync(path.join(root, relative), "utf8");
        const dependencies = [
            ...Array.from(source.matchAll(/\$\(dirname "\$0"\)\/([^"\s]+)/g), (match) => match[1]),
            ...Array.from(source.matchAll(/\bfrom\s+["'](\.[^"']+)["']/g), (match) => match[1]),
        ];
        for (const dependency of dependencies)
            visit(path.posix.normalize(path.posix.join(path.posix.dirname(relative), dependency)));
    }
    visit("githooks/commit-msg");
    const install = path.join(consumer, "node_modules", "@heroiclands", "package-build");
    mkdirSync(install, { recursive: true });
    const extracted = spawnSync(
        "tar",
        ["-xzf", path.join(scratch, manifest.filename), "--strip-components=1", "-C", install],
        { encoding: "utf8" },
    );
    expect(extracted.status, extracted.stderr).toBe(0);
    for (const relative of visited) expect(existsSync(path.join(install, relative))).toBe(true);
    const hook = path.join(install, "githooks/commit-msg");
    expect(runHook(hook, "Co-Authored-By: Codex <codex@openai.com>").status).toBe(1);
    expect(runHook(hook, "Co-Authored-By: Jean-Claude Martin <jean@example.com>").status).toBe(0);
}, 30_000);
