/*
 * This file is part of the Song of Heroic Lands (SoHL) system for Foundry VTT.
 * Copyright (c) 2024-2026 Tom Rodriguez ("Toasty") — <toasty@heroiclands.org>
 *
 * This work is licensed under the GNU General Public License v3.0 (GPLv3).
 * You may copy, modify, and distribute it under the terms of that license.
 *
 * For full terms, see the LICENSE.md file in the project root or visit:
 * https://www.gnu.org/licenses/gpl-3.0.html
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/**
 * The `sohl` knowledgebase's own body passes (#63).
 *
 * `content-build site` publishes a content tree as a website, and almost all of
 * that job is the same for every package. These two rewrites are not: they are
 * driven by a TypeDoc symbol map and a repository layout only this package has,
 * and #63 rules them explicitly per-consumer.
 *
 * They live here rather than in a script in the consuming repository for the
 * same reason `sohl/item-builders.mjs` and `sohl/being-info.mjs` do: a
 * configuration is data and cannot hold a function, so a package-specific table
 * of code is **named** from configuration and resolved from a registry. What is
 * package-specific is the code; what is repository-specific — where the symbol
 * map sits, what the API is served at, which GitHub tree to link into — is
 * options, supplied beside the name.
 *
 * Neither *rewrite* ever fails a build. A `{@link}` the map does not know
 * degrades to a code span, and a relative link that resolves outside the
 * documentation tree becomes a GitHub blob URL. Both are legible to a reader; a
 * broken link or a failed build for a syntax example in prose would not be.
 *
 * Building the bundle is a different matter: a `symbolMap` that is configured
 * and cannot be used fails, loudly, before a page is rendered (#75). Degrading
 * a tag the map does not know is a judgement about *prose*; degrading every tag
 * on the site because the map was never read is a build that lied.
 *
 * @module
 */

import fs from "node:fs";
import path from "node:path";
import log from "loglevel";

/**
 * Reads the TypeDoc symbol map, or an empty one.
 *
 * **Not configuring a map is the empty case, and it is silent.** The map is
 * generated by `npm run docs`, and a knowledgebase build in a repository that
 * has no API documentation should publish prose with `{@link}` tags degraded to
 * code spans rather than refuse to build.
 *
 * **Configuring one that cannot be used is a defect, and it fails the build.**
 * A missing file, a malformed one, a permissions error and a path typo used to
 * be indistinguishable from each other *and* from a correctly configured build
 * with no symbols: a bare `catch` returned `{}` for all five. Nothing then
 * compares an emitted page against what its source asked for, so the first
 * observer of a broken map was a reader who clicked nothing, because every
 * `{@link}` on the published site had quietly become a code span (#75).
 *
 * The path is resolved against the **repository root**, never the process cwd.
 * `site.passOptions.symbolMap` is authored repo-relative, so a cwd-relative
 * read misses the moment `content-build site` is driven from anywhere but the
 * repository root — which is exactly how #51's end-to-end verification, running
 * through `PACKAGE_BUILD_CONFIG` from outside the tree, found this.
 *
 * @param {string|undefined} file - Path to the map, if configured.
 * @param {string|undefined} repoRoot - The repository root to resolve against.
 * @returns {Record<string, string>} Qualified name → API page path.
 * @throws {Error} When a configured map cannot be resolved, read, parsed, or is
 *   not a name → page object.
 */
function readSymbolMap(file, repoRoot) {
    if (!file) return {};

    // Refused rather than quietly resolved against the cwd, which is the
    // defect this function was fixed for: a fallback would let it return.
    if (!path.isAbsolute(file) && !repoRoot) {
        throw new Error(
            `site.passOptions.symbolMap ${JSON.stringify(file)} is relative ` +
                `and no repoRoot was supplied to resolve it against`,
        );
    }
    const resolved = path.resolve(repoRoot ?? "", file);

    let raw;
    try {
        raw = fs.readFileSync(resolved, "utf8");
    } catch (err) {
        throw new Error(
            `site.passOptions.symbolMap ${resolved} cannot be read: ` + `${err.message}`,
        );
    }

    let parsed;
    try {
        parsed = JSON.parse(raw);
    } catch (err) {
        throw new Error(
            `site.passOptions.symbolMap ${resolved} is not valid JSON: ` + `${err.message}`,
        );
    }

    // `[]`, `"x"` and `null` all parse, and then every lookup misses — the same
    // silent degradation reached a different way.
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
        throw new Error(
            `site.passOptions.symbolMap ${resolved} is not an object mapping ` +
                `qualified names to API page paths`,
        );
    }

    // Reported because a map that loaded and a map that loaded empty are
    // otherwise indistinguishable without reading the emitted HTML — and an
    // empty one degrades every tag exactly as a missing one used to.
    log.info(`resolved ${Object.keys(parsed).length} API symbols from ${file}`);
    return parsed;
}

/**
 * Resolves inline TypeDoc `{@link}` / `{@linkcode}` / `{@linkplain}` tags
 * against the API symbol map.
 *
 * - A known target becomes a Markdown link to its page on the API site;
 *   `@linkcode` renders the text as code.
 * - Optional display text (`{@link Target | text}` or `{@link Target text}`)
 *   wins; otherwise the last dotted segment is the link text.
 * - An external URL target becomes a plain Markdown link.
 * - Anything the map does not know — `{@link Symbol.member}` written as a syntax
 *   example, say — degrades to a code span. Never a broken link, never a build
 *   failure.
 *
 * @param {string} body - The markdown body.
 * @param {Record<string, string>} symbols - The symbol map.
 * @param {string} apiBase - Where the generated API documentation is served.
 * @returns {string} The body with every tag resolved.
 */
export function resolveApiLinks(body, symbols, apiBase) {
    return body.replace(/\{@link(code|plain)?\s+([^}]+)\}/g, (_m, kind, inner) => {
        inner = inner.trim();
        let target, text;
        const pipe = inner.indexOf("|");
        const space = inner.search(/\s/);
        if (pipe !== -1) {
            target = inner.slice(0, pipe).trim();
            text = inner.slice(pipe + 1).trim();
        } else if (space !== -1) {
            target = inner.slice(0, space);
            text = inner.slice(space + 1).trim();
        } else {
            target = inner;
            text = "";
        }

        if (/^https?:\/\//.test(target)) {
            return `[${text || target}](${target})`;
        }

        const url = symbols[target];
        const display = text || target.split(".").pop();
        if (url) {
            const href = apiBase + url;
            return kind === "code" ? `[\`${display}\`](${href})` : `[${display}](${href})`;
        }
        return kind === "plain" ? display : `\`${display}\``;
    });
}

/**
 * Rewrites the relative links in a developer-doc body so they resolve on the
 * published site.
 *
 * Developer docs are authored to link one another and the source tree with
 * repository-relative paths, and neither target exists at the same path once
 * rendered. Each link is resolved against the doc's own location:
 *
 * - a `*.md` link landing inside the documentation tree becomes the published
 *   route, preserving any `#anchor`; a `README` is its directory's landing, so
 *   that segment is dropped.
 * - anything else — source, templates, a repository-root `*.md` — becomes its
 *   GitHub blob URL.
 *
 * Absolute URLs, anchor-only links, `mailto:` and site-root links are untouched.
 *
 * @param {string} body - The markdown body.
 * @param {string} docRel - The doc's path relative to the documentation tree.
 * @param {object} options - `{ repoRoot, docsSrc, docsRel, route, blob }`.
 * @returns {string} The body with every relative link rewritten.
 */
export function rewriteRepoLinks(body, docRel, options) {
    const { repoRoot, docsSrc, docsRel, route, blob } = options;
    const docDir = path.dirname(docRel);
    return body.replace(/\]\(([^)]+)\)/g, (whole, raw) => {
        // Peel an optional link title: [text](url "title").
        const sp = raw.search(/\s/);
        const href = sp === -1 ? raw : raw.slice(0, sp);
        const title = sp === -1 ? "" : raw.slice(sp);
        if (/^(https?:|mailto:|tel:|#|\/)/.test(href)) return whole;

        const hash = href.indexOf("#");
        const filePart = hash === -1 ? href : href.slice(0, hash);
        const anchor = hash === -1 ? "" : href.slice(hash);
        if (!filePart) return whole;

        const repoRel = path
            .relative(repoRoot, path.resolve(docsSrc, docDir, filePart))
            .replace(/\\/g, "/");

        let out;
        if (repoRel.startsWith(`${docsRel}/`) && repoRel.endsWith(".md")) {
            const rel2 = repoRel.slice(docsRel.length + 1, -3).toLowerCase();
            const devPath = path.basename(rel2) === "readme" ? path.posix.dirname(rel2) : rel2;
            out = `${route}${devPath === "." ? "" : `${devPath}/`}${anchor}`;
        } else {
            out = `${blob}${repoRel}${anchor}`;
        }
        return `](${out}${title})`;
    });
}

/**
 * The `sohl` knowledgebase pass bundle, built from its options.
 *
 * A pass bundle is two optional hooks the page renderer calls around wikilink
 * resolution, and the order matters:
 *
 * - `beforeLinks` runs on every page, before wikilinks resolve, because a
 *   `{@link}` tag may sit inside prose a wikilink also touches.
 * - `afterLinks` runs only on pages from an **extra tree** — the documentation
 *   tree — because repository-relative links are a property of how those pages
 *   are authored, not of content notes.
 *
 * Both run inside code-fence protection, so neither can rewrite a fenced example.
 *
 * @param {object} options - Resolved from `site.passOptions`.
 * @param {string} [options.symbolMap] - Path to the TypeDoc symbol map,
 *   relative to `repoRoot`. Absent means no API links; present and unusable is
 *   a build failure.
 * @param {string} [options.apiBase] - Where the API documentation is served.
 * @param {string} [options.blob] - GitHub blob base for repository files.
 * @param {string} options.repoRoot - The repository root, for relative paths.
 * @returns {{beforeLinks: Function, afterLinks: Function}} The bundle.
 * @throws {Error} When a configured `symbolMap` cannot be resolved, read,
 *   parsed, or is not a name → page object.
 */
export function sohlKbPass(options) {
    const symbols = readSymbolMap(options.symbolMap, options.repoRoot);
    const apiBase = options.apiBase ?? "";
    return {
        beforeLinks: (text) => resolveApiLinks(text, symbols, apiBase),
        afterLinks: (text, page) =>
            page.tree ?
                rewriteRepoLinks(text, page.rel, {
                    repoRoot: options.repoRoot,
                    docsSrc: page.tree.from,
                    docsRel: page.tree.rel,
                    route: page.tree.route,
                    blob: options.blob ?? "",
                })
            :   text,
    };
}
